// <auto-generated />
using System;
using Do_An.Areas.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Do_An.Migrations
{
    [DbContext(typeof(DPContext))]
    partial class DPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Do_An.Areas.Admin.Models.ChiTietHoaDonModel", b =>
                {
                    b.Property<int>("IdCTHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("idSanPham")
                        .HasColumnType("int");

                    b.HasKey("IdCTHD");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("Do_An.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.Property<int>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NgayLap")
                        .HasColumnType("int");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.HasKey("IdHoaDon");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Do_An.Areas.Admin.Models.LoaiSanPhamModel", b =>
                {
                    b.Property<int>("IdLoaiSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLoaiSp");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("Do_An.Areas.Admin.Models.LoaiUserModel", b =>
                {
                    b.Property<int>("idLoaiUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("idLoaiUser");

                    b.ToTable("LoaiUser");
                });

            modelBuilder.Entity("Do_An.Areas.Admin.Models.SanPhamModel", b =>
                {
                    b.Property<int>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("GiaBan")
                        .HasColumnType("real");

                    b.Property<float>("GiaNhap")
                        .HasColumnType("real");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDLoaiSp")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiSanPhamIdLoaiSp")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdSanPham");

                    b.HasIndex("LoaiSanPhamIdLoaiSp");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("Do_An.Areas.Admin.Models.UserModel", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLoaiUser")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiUseridLoaiUser")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("NgayLap")
                        .HasColumnType("int");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.HasIndex("LoaiUseridLoaiUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Do_An.Areas.Admin.Models.SanPhamModel", b =>
                {
                    b.HasOne("Do_An.Areas.Admin.Models.LoaiSanPhamModel", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("LoaiSanPhamIdLoaiSp");
                });

            modelBuilder.Entity("Do_An.Areas.Admin.Models.UserModel", b =>
                {
                    b.HasOne("Do_An.Areas.Admin.Models.LoaiUserModel", "LoaiUser")
                        .WithMany("UserModels")
                        .HasForeignKey("LoaiUseridLoaiUser");
                });
#pragma warning restore 612, 618
        }
    }
}
